version: '3.7'

services:

  postgres:
    container_name: 'examples.postgres'
    restart: always
    image: postgres
    build:
      context: ./SQL
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=exampledb
    networks:
      - internal

  webapp:
    container_name: 'examples.webapp'
    restart: always
    image: app
    build:
      context: ./
      dockerfile: app.dockerfile
    ports:
      - "8080:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge
